### ISSUE TITLE
Request: Safari Extension

### ISSUE THREAD

**Issue by remypanicker** [TheBox193/diningin-enhancements#1]
Not sure how much work would go into bundling a Safari extension, but I imagine there is a lot of overlap since the Chrome extension is injecting JS.

[Safari Extensions Conversion Guide - Converting Chrome Extensions](https://developer.apple.com/library/safari/documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html)

**Comment by TheBox193** [comment]
Depending on interest I may consider a build for Safari, but right now the main focus will remain Chrome. It looks like a few of the APIs are different when it comes to storage which is being used for the settings page.
